---

- hosts: ubuntu
  become: true
  tasks:

  - name: update and upgrade packages
    apt:
      update_cache: yes
      upgrade: 'yes'

  - name: install tree package
    apt:
      name: tree
      state: present

  - name: install htop package
    apt:
      name: htop
      state: present
  - name: install nginx package
    apt:
      name: nginx
      state: present
  - name: install nano package
    apt:
      name: nano
      state: present
  - name: update repo index
    apt:
      update_cache: yes 

