---

- hosts: ubuntu
  become: true
  tasks:

  - name: update and upgrade packages
    apt:
      update_cache: yes
      upgrade: 'yes'
      

  - name: uninstall htop package
    apt:
      name: htop
      state: absent
  - name: uninstall nginx package
    apt:
      name: nginx
      state: absent
  - name: uninstall nano package
    apt:
      name: nano
      state: absent
  - name: update repo index
    apt:
      update_cache: yes 

