---

- hosts: all
  become: true
  tasks:

  - name: install htop package
    yum:
      name: htop
      state: absent
  - name: install nginx package
    yum:
      name: nginx
      state: absent
  - name: install nano package
    yum:
      name: nano
      state: absent
  - name: update repo index
    yum:
      update_cache: yes 

